import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Topbar from "@/components/Shared/Topbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-white bg-opacity-20 flex flex-col items-center min-h-screen w-screen`}
      >
        <div className="fixed top-0 left-0">
          <Topbar />
        </div>
        <div className="flex flex-1 pt-20 bg-[#161815]">{children}</div>
      </body>
    </html>
  );
}
